server:
  port: 8081
spring:
  application:
    name: EVENT-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:8080
          predicates:
            - Path=/users/**

        - id: EVENT-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/events/**







